[package]
name = "cargo-llvm-lines"
version = "0.4.15"
authors = ["David Tolnay <dtolnay@gmail.com>", "Nicholas Nethercote <nnethercote@mozilla.com>"]
license = "MIT OR Apache-2.0"
description = "Count the number of lines of LLVM IR across all instantiations of a generic function."
repository = "https://github.com/dtolnay/cargo-llvm-lines"
documentation = "https://github.com/dtolnay/cargo-llvm-lines"
categories = ["development-tools::cargo-plugins", "development-tools::debugging"]
edition = "2018"
readme = "README.md"

[dependencies]
atty = "0.2"
cargo-subcommand-metadata = "0.1"
clap = { version = "3.1", features = ["derive", "wrap_help"] }
rustc-demangle = "0.1"
tempdir = "0.3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
